### ISSUE TITLE
Result::unwrap()` on an `Err` value: FrontrunEvmError(Transaction(NonceTooLow { tx: 1, state: 3 }))', 

### ISSUE THREAD

**Issue by ephz3nt** [mouseless-eth/rusty-sando#8]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: FrontrunEvmError(Transaction(NonceTooLow { tx: 1, state: 3 }))', src/simulate/make_sandwich.rs:420:10

looks searcher nonce != 0 will simulate failed

**Comment by luncht1me** [comment]
Anything to add to this? How did you resolve? Haven't taken a dive yet.

**Comment by jamil-wittmann** [comment]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: FrontrunEvmError(Transaction(NonceTooLow { tx: 1, state: 6 }))', src/simulate/make_sandwich.rs:439:10


I'm running into the same issue, although my error output is a tiny different due to some print statement additions. Is this normal behavior from time to time or is this something I need to fix before the bot functions properly? I have everything up and running, but at the moment right now this error seems to be the barrier for the bot to start actually executing. 

Have you been able to figure this error out or get the bot to function fully? @ephz3nt @luncht1me

**Comment by DaveBennet** [comment]
I see this issue is closed, how did you solve it? getting the same problem, tracing reveals that the tx nonce is grabbed from the victim nonce but the state nonce is the searcher wallets. not sure why
